dist: bionic
sudo: required
addons:
before_install:
  - printf "\n# Used by proxy-chain NPM package tests\n127.0.0.1 localhost-test\n" | sudo tee -a /etc/hosts
language: node_js
node_js:
  - "8"
  - "9"
  - "10"
  - "11"
  - "12"
script:
  - npm run lint
  - npm test
